name: dbt CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  run_dbt_and_test:
    name: Run dbt models and tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # --- NOUVELLE ÉTAPE DE TEST ---
      - name: Test secret access
        run: echo "La valeur du secret pour le compte est [${{ secrets.DBT_SNOWFLAKE_ACCOUNT }}]"
      # --------------------------------

      - name: Install dbt dependencies
        run: pip install dbt-snowflake

      - name: Configure dbt profile
        run: |
          mkdir -p ~/.dbt
          echo "analytics:" > ~/.dbt/profiles.yml
          echo "  target: dev" >> ~/.dbt/profiles.yml
          echo "  outputs:" >> ~/.dbt/profiles.yml
          echo "    dev:" >> ~/.dbt/profiles.yml
          echo "      type: snowflake" >> ~/.dbt/profiles.yml
          echo "      account: ${{ secrets.DBT_SNOWFLAKE_ACCOUNT }}" >> ~/.dbt/profiles.yml
          echo "      user: ${{ secrets.DBT_SNOWFLAKE_USER }}" >> ~/.dbt/profiles.yml
          echo "      password: ${{ secrets.DBT_SNOWFLAKE_PASSWORD }}" >> ~/.dbt/profiles.yml
          echo "      role: SYSADMIN" >> ~/.dbt/profiles.yml
          echo "      database: WIKI_STREAMING_PROJECT" >> ~/.dbt/profiles.yml
          echo "      warehouse: COMPUTE_WH" >> ~/.dbt/profiles.yml
          echo "      schema: ANALYTICS" >> ~/.dbt/profiles.yml
          echo "      threads: 4" >> ~/.dbt/profiles.yml
      
      - name: Display profiles.yml for debugging
        run: cat ~/.dbt/profiles.yml

      - name: Run dbt debug
        run: dbt debug

      - name: Run dbt commands
        run: |
          dbt run
          dbt snapshot
          dbt test